// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PJ_SEM03.Models;

#nullable disable

namespace PJ_SEM03.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240130155421_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PJ_SEM03.Models.Cart", b =>
                {
                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("product_quantity")
                        .HasColumnType("int");

                    b.HasKey("product_id", "user_id");

                    b.HasIndex("user_id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            product_id = 1,
                            user_id = "1",
                            product_quantity = 2
                        },
                        new
                        {
                            product_id = 2,
                            user_id = "2",
                            product_quantity = 1
                        },
                        new
                        {
                            product_id = 3,
                            user_id = "3",
                            product_quantity = 3
                        });
                });

            modelBuilder.Entity("PJ_SEM03.Models.Feedback", b =>
                {
                    b.Property<int>("feedback_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("feedback_id"));

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("feedback_content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feedback_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feedback_fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feedback_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("product_id")
                        .HasColumnType("int");

                    b.HasKey("feedback_id");

                    b.HasIndex("UserId");

                    b.HasIndex("product_id");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            feedback_id = 1,
                            feedback_content = "So easy to register and login! Like it",
                            feedback_email = "khai@gmail.com",
                            feedback_fullname = "Bui Tuan Khai",
                            feedback_type = "Account"
                        },
                        new
                        {
                            feedback_id = 2,
                            feedback_content = "I love promotion of this month",
                            feedback_email = "trung@gmail.com",
                            feedback_fullname = "Nguyen Thanh Trung",
                            feedback_type = "Promotion"
                        },
                        new
                        {
                            feedback_id = 3,
                            feedback_content = "The system run smoothly",
                            feedback_email = "phat@gmail.com",
                            feedback_fullname = "Ngo Thinh Phat",
                            feedback_type = "System"
                        },
                        new
                        {
                            feedback_id = 4,
                            feedback_content = "The staffs are so friendly",
                            feedback_email = "tram@gmail.com",
                            feedback_fullname = "Tran Bao Huyen Tram",
                            feedback_type = "Other"
                        });
                });

            modelBuilder.Entity("PJ_SEM03.Models.GiftCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplyFor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Describe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("giftName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("percentReduce")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GiftCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplyFor = "Medical, Education, Scientific",
                            Describe = "Reduce 5%",
                            giftName = "Welcome",
                            percentReduce = 5
                        },
                        new
                        {
                            Id = 2,
                            ApplyFor = "Medical, Education, Scientific",
                            Describe = "Reduce 10%",
                            giftName = "Goodbye",
                            percentReduce = 10
                        });
                });

            modelBuilder.Entity("PJ_SEM03.Models.Order", b =>
                {
                    b.Property<int>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("order_id"));

                    b.Property<int?>("AppliedGiftCodeId")
                        .HasColumnType("int");

                    b.Property<string>("order_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("order_datetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("order_phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("order_total")
                        .HasColumnType("int");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("order_id");

                    b.HasIndex("AppliedGiftCodeId");

                    b.HasIndex("user_id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            order_id = 1,
                            order_address = "HCM",
                            order_code = "ORD001",
                            order_datetime = new DateTime(2024, 1, 30, 22, 54, 20, 684, DateTimeKind.Local).AddTicks(5172),
                            order_phone = "123",
                            order_status = "Processing",
                            order_total = 100,
                            user_id = "1"
                        },
                        new
                        {
                            order_id = 2,
                            order_address = "Ca Mau",
                            order_code = "ORD001",
                            order_datetime = new DateTime(2024, 1, 30, 22, 54, 20, 684, DateTimeKind.Local).AddTicks(5198),
                            order_phone = "124",
                            order_status = "Delivered",
                            order_total = 200,
                            user_id = "2"
                        });
                });

            modelBuilder.Entity("PJ_SEM03.Models.OrderDetail", b =>
                {
                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<int>("order_id")
                        .HasColumnType("int");

                    b.Property<int>("product_quantity")
                        .HasColumnType("int");

                    b.HasKey("product_id", "order_id");

                    b.HasIndex("order_id");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            product_id = 1,
                            order_id = 1,
                            product_quantity = 2
                        },
                        new
                        {
                            product_id = 3,
                            order_id = 1,
                            product_quantity = 3
                        },
                        new
                        {
                            product_id = 2,
                            order_id = 2,
                            product_quantity = 4
                        },
                        new
                        {
                            product_id = 4,
                            order_id = 2,
                            product_quantity = 1
                        });
                });

            modelBuilder.Entity("PJ_SEM03.Models.Product", b =>
                {
                    b.Property<int>("product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("product_id"));

                    b.Property<int?>("GiftCodeId")
                        .HasColumnType("int");

                    b.Property<string>("product_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("product_percent")
                        .HasColumnType("int");

                    b.Property<int>("product_price")
                        .HasColumnType("int");

                    b.Property<int>("product_quantity")
                        .HasColumnType("int");

                    b.Property<int>("product_star")
                        .HasColumnType("int");

                    b.Property<string>("product_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("product_id");

                    b.HasIndex("GiftCodeId");

                    b.ToTable("Products", (string)null);

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            product_id = 1,
                            product_description = "What is Costar Evening Primrose Oil? Uses and correct usage\nCostar Evening Primrose Oil is a health care product extracted from evening primrose essential oil. Supports anti-oxidation and reduces symptoms of hot flashes in postmenopausal and premenopausal women. This article will introduce more information about the ingredients, uses, usage and intended users of Costar pills",
                            product_img = "https://data-service.pharmacity.io/pmc-upload-media/production/pmc-ecm-core/products/P17315_1.jpg",
                            product_name = "Costar Evening Primrose Oil",
                            product_percent = 10,
                            product_price = 90,
                            product_quantity = 10,
                            product_star = 5,
                            product_type = "Medical"
                        },
                        new
                        {
                            product_id = 2,
                            product_description = "The Bresser Science ETD-201 is a high-quality stereo microscope with transmitted and incident light. It is ideally suited for use in schools and universities as well as for the training of apprentices and in the field of electronics. The 360° rotatable binocular head allows comfortable viewing for both left and right-handed users. The magnification range of 20x to 80x can be extended with the included Barlow lens to 40x to 160x. The LED lighting is continuously dimmable and can be operated with batteries or the included power supply. The microscope is equipped with a 2x and 4x objective and a pair of 10x wide field eyepieces. The interpupillary distance and diopter adjustment are individually adjustable. The microscope is supplied with a dust cover and 5 prepared slides.",
                            product_img = "https://maykhoahoc.com/images/thumbnails/550/450/detailed/4/tu-bao-quan-thuoc-duoc-lieu-vacxin-haier-hbc-260-gia-re.jpg",
                            product_name = "Bresser Science ETD-201",
                            product_percent = 20,
                            product_price = 100,
                            product_quantity = 10,
                            product_star = 4,
                            product_type = "Scientific"
                        },
                        new
                        {
                            product_id = 3,
                            product_description = "Description1",
                            product_img = "https://www.bresser.de/out/pictures/generated/product/1/380_340_75/8851000_1.jpg",
                            product_name = "Course 2",
                            product_percent = 10,
                            product_price = 30,
                            product_quantity = 10,
                            product_star = 5,
                            product_type = "Education"
                        },
                        new
                        {
                            product_id = 4,
                            product_description = "What is Costar Evening Primrose Oil? Uses and correct usage\nCostar Evening Primrose Oil is a health care product extracted from evening primrose essential oil. Supports anti-oxidation and reduces symptoms of hot flashes in postmenopausal and premenopausal women. This article will introduce more information about the ingredients, uses, usage and intended users of Costar pills",
                            product_img = "https://data-service.pharmacity.io/pmc-upload-media/production/pmc-ecm-core/products/P17480_1.jpg",
                            product_name = "Acetylcystein",
                            product_percent = 50,
                            product_price = 90,
                            product_quantity = 10,
                            product_star = 5,
                            product_type = "Medical"
                        },
                        new
                        {
                            product_id = 5,
                            product_description = "The Bresser Science ETD-201 is a high-quality stereo microscope with transmitted and incident light. It is ideally suited for use in schools and universities as well as for the training of apprentices and in the field of electronics. The 360° rotatable binocular head allows comfortable viewing for both left and right-handed users. The magnification range of 20x to 80x can be extended with the included Barlow lens to 40x to 160x. The LED lighting is continuously dimmable and can be operated with batteries or the included power supply. The microscope is equipped with a 2x and 4x objective and a pair of 10x wide field eyepieces. The interpupillary distance and diopter adjustment are individually adjustable. The microscope is supplied with a dust cover and 5 prepared slides.",
                            product_img = "https://maykhoahoc.com/images/thumbnails/550/450/detailed/4/tu-bao-quan-vacxine-thuoc-haier-hbc-150-gia-re.png",
                            product_name = "Adapter (LEN)",
                            product_percent = 15,
                            product_price = 100,
                            product_quantity = 10,
                            product_star = 4,
                            product_type = "Scientific"
                        },
                        new
                        {
                            product_id = 6,
                            product_description = "Description1",
                            product_img = "https://www.bresser.de/out/pictures/generated/product/1/380_340_75/8851000_1.jpg",
                            product_name = "Course 1",
                            product_percent = 0,
                            product_price = 30,
                            product_quantity = 10,
                            product_star = 0,
                            product_type = "Education"
                        });
                });

            modelBuilder.Entity("PJ_SEM03.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("user_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_fullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7dc95eda-91ef-4ae5-ad27-dffe4b73a2fb",
                            Email = "admin@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEBB11QRaTvVV9NYN1B80a7Yf2Ox+JlQRZ0Y38r4H33HkHkIfD95kof3LJMpdl1lu9Q==",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            SecurityStamp = "df7dc811-501e-4552-8ff8-183660580424",
                            TwoFactorEnabled = false,
                            UserName = "admin",
                            user_fullName = "admin"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d36490ce-f9ba-4866-97f8-3de8083b2d53",
                            Email = "phat@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAENlkobPLeSMyOFFVNc7fptTW+Q0vRIPjp8nG/8nPiTCE3n7R5CPcXexK9p9CE0NzZw==",
                            PhoneNumberConfirmed = false,
                            Role = "Member",
                            SecurityStamp = "0557984a-144a-4d14-8a66-08910a4c9d6e",
                            TwoFactorEnabled = false,
                            UserName = "phat",
                            user_fullName = "Ngo Thinh Phat"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a8f74b16-32fb-4999-ba3a-98ec4518507e",
                            Email = "khai@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEPNlVMlVmz8evPgxWsRuZVO7Xvu7MukqxoTmcTo74clSuLeNQbjyXxnQdllWikCuvQ==",
                            PhoneNumberConfirmed = false,
                            Role = "Member",
                            SecurityStamp = "9bd7f0f3-2a01-433a-8fa4-313e70b7d89f",
                            TwoFactorEnabled = false,
                            UserName = "khai",
                            user_fullName = "Bui Tuan Khai"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7cbc36d1-07eb-422f-90de-bcf742be2e5e",
                            Email = "tram@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEL/3tRXi/i0wd4h0wSC8ktatWUqTmmVC6HTaOIK69fX5WV7khgy5t+psxp6sIfqvUA==",
                            PhoneNumberConfirmed = false,
                            Role = "Member",
                            SecurityStamp = "c1e41e80-4bd7-4cca-8801-b72bd157684e",
                            TwoFactorEnabled = false,
                            UserName = "tram",
                            user_fullName = "Tran Bao Huyen Tram"
                        });
                });

            modelBuilder.Entity("PJ_SEM03.Models.Education", b =>
                {
                    b.HasBaseType("PJ_SEM03.Models.Product");

                    b.Property<string>("edu_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("edu_id")
                        .HasColumnType("int");

                    b.Property<string>("edu_subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("edu_teacher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Educations", (string)null);
                });

            modelBuilder.Entity("PJ_SEM03.Models.Medical", b =>
                {
                    b.HasBaseType("PJ_SEM03.Models.Product");

                    b.Property<string>("med_brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("med_id")
                        .HasColumnType("int");

                    b.Property<string>("med_sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("med_uses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Medicals", (string)null);
                });

            modelBuilder.Entity("PJ_SEM03.Models.Scientific", b =>
                {
                    b.HasBaseType("PJ_SEM03.Models.Product");

                    b.Property<string>("sci_brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sci_id")
                        .HasColumnType("int");

                    b.Property<string>("sci_uses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Scientifics", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PJ_SEM03.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PJ_SEM03.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PJ_SEM03.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PJ_SEM03.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PJ_SEM03.Models.Cart", b =>
                {
                    b.HasOne("PJ_SEM03.Models.Product", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PJ_SEM03.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PJ_SEM03.Models.Feedback", b =>
                {
                    b.HasOne("PJ_SEM03.Models.User", null)
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId");

                    b.HasOne("PJ_SEM03.Models.Product", null)
                        .WithMany("Feedbacks")
                        .HasForeignKey("product_id");
                });

            modelBuilder.Entity("PJ_SEM03.Models.Order", b =>
                {
                    b.HasOne("PJ_SEM03.Models.GiftCode", "AppliedGiftCode")
                        .WithMany()
                        .HasForeignKey("AppliedGiftCodeId");

                    b.HasOne("PJ_SEM03.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppliedGiftCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PJ_SEM03.Models.OrderDetail", b =>
                {
                    b.HasOne("PJ_SEM03.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PJ_SEM03.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PJ_SEM03.Models.Product", b =>
                {
                    b.HasOne("PJ_SEM03.Models.GiftCode", "GiftCode")
                        .WithMany()
                        .HasForeignKey("GiftCodeId");

                    b.Navigation("GiftCode");
                });

            modelBuilder.Entity("PJ_SEM03.Models.Education", b =>
                {
                    b.HasOne("PJ_SEM03.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("PJ_SEM03.Models.Education", "product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PJ_SEM03.Models.Medical", b =>
                {
                    b.HasOne("PJ_SEM03.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("PJ_SEM03.Models.Medical", "product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PJ_SEM03.Models.Scientific", b =>
                {
                    b.HasOne("PJ_SEM03.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("PJ_SEM03.Models.Scientific", "product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PJ_SEM03.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("PJ_SEM03.Models.Product", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Feedbacks");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("PJ_SEM03.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Feedbacks");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
